org.gradle.jvmargs=-Xmx1G

# https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.+
fabric_api_version=0.156.0+26.2

mod_version=1.7.2-alpha.1
maven_group=com.arematics
archives_base_name=AdvancedChatLog

advancedchat_version=26.2-1.7.2-alpha.1
# https://jitpack.io/#sakura-ryoko/malilib
malilib_version=0.29.3
# 1.18.42+ is required for JDK 25
lombok_version=1.18.46
modmenu_version=20.0.1
